version: '3.8'

services:
  db:
    image: "mysql:5.7"
    restart: "unless-stopped"
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=magento
      - MYSQL_PASSWORD=password
    networks:
      - magento-docker-network
  web:
    build:
      context: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    networks:
      - magento-docker-network
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    networks:
      - magento-docker-network
networks:
  magento-docker-network:

volumes:
  db:
    name: learn-maria-mage-01
